spring:
  cloud:
       discovery:
                enabled: true
  application:
    name: sicred-voting
  data:
     mongodb:
        uri: mongodb://localhost:27017/SicredVoting?serverSelectionTimeoutMS=1000&connectTimeoutMS=1000   
        
baseurl:
      v1: sicred/voting/v1

server:
  port: 8000 

feign:
    cpfValidator:
            url: https://user-info.herokuapp.com/
            name: users
   

    

