spring:
  cloud:
       discovery:
                enabled: true
  application:
    name: sicred-voting
  data:
     mongodb:
        uri: mongodb://localhost:27017/SicredVoting?serverSelectionTimeoutMS=1000&connectTimeoutMS=1000   
        
mongodb.encrypt:
  keys:
    - version: 1
      key: hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=

baseurl:
      v1: sicred/voting/v1

server:
  port: 8000
  
   
eureka:
   server:
      enableSelfPreservation: false
   instance:
       leaseRenewalIntervalInSeconds: 1
       leaseExpirationDurationInSeconds: 2
       instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
   client:
    register-with-eureka: true
    fetch-registry: true
    lease:
      duration: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  


    

