spring:
  cloud:
       discovery:
                enabled: true
  application:
    name: sicred-voting

        
baseurl:
      v1: sicred/voting/v1  
 
feign:
    cpfValidator:
            url: https://user-info.herokuapp.com/
            name: users